### ISSUE TITLE
Missing kSecTrustResultRecoverableTrustFailure

### ISSUE THREAD

**Issue by CptLeeChuck** [quellish/PublicKeyPinningExample#1]
Hello,

first of all thank you so much for this great piece of work! One comment, for my understanding you need to verify trustResult not only for **kSecTrustResultUnspecified** but also **kSecTrustResultRecoverableTrustFailure** (which could be the case as well in some scenarios)
I'm talking about this method: 

```
- (NSURLCredential *) credentialForServerTrustInProtectionSpace:(NSURLProtectionSpace *)protectionSpace {
    NSLog(@"DELEGATE 2");
    NSURLCredential         *result             = nil;
    OSStatus                status              = errSecSuccess;
    SecTrustResultType      trustResult         = kSecTrustResultFatalTrustFailure;
    SecTrustRef             trust               = NULL;


    result = [[NSURLCredentialStorage sharedCredentialStorage] defaultCredentialForProtectionSpace:protectionSpace];
    if (result == nil){
        trust = [protectionSpace serverTrust];
        status = SecTrustEvaluate(trust, &trustResult);
        NSLog(@"-- 1");
        if (status == errSecSuccess){
            NSLog(@"-- 2 %d", trustResult);
            switch (trustResult){
                case kSecTrustResultProceed:
                case kSecTrustResultUnspecified:{
                    NSLog(@"unspecified");
                    if ([self canAllowServerTrustForProtectionSpace:protectionSpace]){
                        result = [NSURLCredential credentialForTrust:trust];
                        [[NSURLCredentialStorage sharedCredentialStorage] setDefaultCredential:result forProtectionSpace:protectionSpace];
                    }
                }
                case kSecTrustResultRecoverableTrustFailure:{
                    NSLog(@"kSecTrustResultRecoverableTrustFailure");
                    if ([self canAllowServerTrustForProtectionSpace:protectionSpace]){
                        result = [NSURLCredential credentialForTrust:trust];
                        [[NSURLCredentialStorage sharedCredentialStorage] setDefaultCredential:result forProtectionSpace:protectionSpace];
                    }
                }
                    break;
                default:
                    break;
            }
        }
    }
    return result;
}
```

**Comment by quellish** [comment]
For SSL certificate pinning, almost all the cases where the trust evaluation would result in `kSecTrustResultRecoverableTrustFailure` would be considered failures. `kSecTrustResultRecoverableTrustFailure` means that with the given trust evaluation settings there was a failure, but a change in settings may result in success. With SSL pinning you are comparing a white listed credential against what is coming in over the wire - which allows you to be far more strict than in more common SSL trust evaluation scenarios. The credential either is, or isn't the whitelisted credential. For example, if the certificate(s) are expired you would want the evaluation to fail - even though the trust evaluation would report `kSecTrustResultRecoverableTrustFailure`. 

Your application's requirements may be different, and you may want to handle some of these scenarios differently (for example, in the case of expired credentials requesting new ones over a secure channel). Recovering from trust evaluation failures such as `kSecTrustResultRecoverableTrustFailure` is more of an application concern and is beyond the scope of this example. See [Recovering From a Trust Failure](https://developer.apple.com/library/ios/documentation/Security/Conceptual/CertKeyTrustProgGuide/iPhone_Tasks/iPhone_Tasks.html#//apple_ref/doc/uid/TP40001358-CH208-SW8) for more information.
